apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: verdure-eshop-statestore
  namespace: eshop
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: State.RedisPassword
      key: State.RedisPassword
  - name: actorStateStore
    value: "true"
auth:
  secretStore: verdure-eshop-secretstore
scopes:
- basket-api
- ordering-api